#!/bin/bash 
MID_PATH='/home/nam/work/RunPSI2013/data/mid/'
RAWTREE_PATH='/home/nam/work/RunPSI2013/data/root/rawtree/'
ANALYSEDTREE_PATH='/home/nam/work/RunPSI2013/data/root/analysedtree/'
ALCAPANAHIST_PATH='/home/nam/work/RunPSI2013/data/root/alcapanahist/'
ROOTANAHIST_PATH='/home/nam/work/RunPSI2013/data/root/rootanahist/'

if [[ -z "$1" ]]; then
	echo "A run number is needed!"
	exit 0
fi

runNo=$(printf "%.5d" "$1")
inputfile=$RAWTREE_PATH'tree'$runNo'.root'
analysedtreeout=$ANALYSEDTREE_PATH'anatree'$runNo'.root'

if [[ ! -f $analysedtreeout ]]; then
	./rootana -i $inputfile -o $analysedtreeout
else 
	echo $analysedtreeout "existed!"
fi
