#!/usr/bin/env python
import os.path
import string
import subprocess
import re
import types

MID_PATH='/home/nam/work/RunPSI2013/data/mid/'
RAWTREE_PATH='/home/nam/work/RunPSI2013/data/root/rawtree/'
ANALYSEDTREE_PATH='/home/nam/work/RunPSI2013/data/root/analysedtree/'
ALCAPANAHIST_PATH='/home/nam/work/RunPSI2013/data/root/alcapanahist/'
ROOTANAHIST_PATH='/home/nam/work/RunPSI2013/data/root/rootanahist/'


def process_run(runNo):
    """Process a run
    """
    inputfile = RAWTREE_PATH + 'tree%05d.root' % runNo
    analysedtreeout = ROOTANAHIST_PATH + 'anatree%05d_Amp.root' % (runNo)
    #elif isinstance(timecut,types.ListType):
        #analysedtreeout = ROOTANAHIST_PATH + \
                #'anatree%05d_%d_%dns.root' % (runNo,timecut[0], timecut[1])
        #pass

    if os.path.isfile(analysedtreeout):
        print analysedtreeout + ' existed, skipping ...'
    else:
        command = ['./rootana', '-i', inputfile, '-o', analysedtreeout]
        subprocess.call(command)
    return

def process_all_runs(runlist_filename):
    """Fetch run list from a text file, and run
    """
    listfile = open(runlist_filename, 'r')
    runlist = [string.atoi(line.strip()) for line in listfile]
    for runNo in runlist:
        process_run(runNo)
    pass

###########
runlist_path = '../work/nam/'
runlist_file = 'Si16 passive_1.06_runs'
#runlist_file = 'Al100_1.09_runs'

subprocess.call(['make'])
process_all_runs(runlist_path + runlist_file)
