{
  //////////////////////////////////////////////////////////////////////////////
  // USER DEFINED VARIABLES
  const char IFNAME_P[]     = "data/Ti50/tms/tm.p.2layer.mudist.root";
  const char IFNAME_D[]     = "data/Ti50/tms/tm.d.2layer.mudist.root";
  // const char IFNAME_T[]     = "~/data/R15b/al50ttm.root";
  // const char IFNAME_A[]     = "~/data/R15b/al50atm.root";
  //////////////////////////////////////////////////////////////////////////////

  TFile* fp = new TFile(IFNAME_P);
  TFile* fd = new TFile(IFNAME_D);
  // TFile* ft = new TFile(IFNAME_T);
  // TFile* fa = new TFile(IFNAME_A);
  RooUnfoldResponse* resp_pl = (RooUnfoldResponse*)fp->Get("SiL_TM");
  RooUnfoldResponse* resp_pr = (RooUnfoldResponse*)fp->Get("SiR_TM");
  RooUnfoldResponse* resp_dl = (RooUnfoldResponse*)fd->Get("SiL_TM");
  RooUnfoldResponse* resp_dr = (RooUnfoldResponse*)fd->Get("SiR_TM");
  // RooUnfoldResponse* resp_tl = (RooUnfoldResponse*)ft->Get("SiL_TM");
  // RooUnfoldResponse* resp_tr = (RooUnfoldResponse*)ft->Get("SiR_TM");
  // RooUnfoldResponse* resp_al = (RooUnfoldResponse*)fa->Get("SiL_TM");
  // RooUnfoldResponse* resp_ar = (RooUnfoldResponse*)fa->Get("SiR_TM");
  TH2* htm_pl = resp_pl->Hresponse(); TH2* htm_pr = resp_pr->Hresponse();
  TH2* htm_dl = resp_dl->Hresponse(); TH2* htm_dr = resp_dr->Hresponse();
  // TH2* h_tl = resp_tl->Hresponse(); TH2* h_tr = resp_tr->Hresponse();
  // TH2* h_al = resp_al->Hresponse(); TH2* h_ar = resp_ar->Hresponse();
  TH2* hdm_pl = (TH2*)fp->Get("SiL_DM"); TH2* hdm_pr = (TH2*)fp->Get("SiR_DM");
  TH2* hdm_dl = (TH2*)fd->Get("SiL_DM"); TH2* hdm_dr = (TH2*)fd->Get("SiR_DM");
  TPaveText* txt_l = new TPaveText(10e3, 2e3, 14e3, 5e3);
  TPaveText* txt_r = new TPaveText(10e3, 2e3, 14e3, 5e3);
  txt_l->AddText("Ti 50#mum Target");
  txt_r->AddText("Ti 50#mum Target");
  htm_pl->SetTitle("Simulated Left Telescope Proton Response;E_{meas} [keV];E_{true} [keV]");
  htm_pr->SetTitle("Simulated Right Telescope Proton Response;E_{meas} [keV];E_{true} [keV]");
  htm_dl->SetTitle("Simulated Left Telescope Deuteron Response;E_{meas} [keV];E_{true} [keV]");
  htm_dr->SetTitle("Simulated Right Telescope Deuteron Response;E_{meas} [keV];E_{true} [keV]");
  // h_tl->SetTitle("SiL Triton Response;E_{meas} [keV];E_{true} [keV]");
  // h_tr->SetTitle("SiR Triton Response;E_{meas} [keV];E_{true} [keV]");
  // h_al->SetTitle("SiL Alpha Response;E_{meas} [keV];E_{true} [keV]");
  // h_ar->SetTitle("SiR Alpha Response;E_{meas} [keV];E_{true} [keV]");
  hdm_pl->SetTitle("Simulated Left Telescope Proton Energy Loss;E_{true} [keV];E_{loss} [keV]");
  hdm_pr->SetTitle("Simulated Right Telescope Proton Energy Loss;E_{true} [keV];E_{loss} [keV]");
  hdm_dl->SetTitle("Simulated Left Telescope Deuteron Energy Loss;E_{true} [keV];E_{loss} [keV]");
  hdm_dr->SetTitle("Simulated Right Telescope Deuteron Energy Loss;E_{true} [keV];E_{loss} [keV]");
  htm_pl->GetXaxis()->SetRangeUser(0, 15e3); htm_pl->GetYaxis()->SetRangeUser(0, 15e3);
  htm_pr->GetXaxis()->SetRangeUser(0, 15e3); htm_pr->GetYaxis()->SetRangeUser(0, 15e3);
  htm_dl->GetXaxis()->SetRangeUser(0, 15e3); htm_dl->GetYaxis()->SetRangeUser(0, 15e3);
  htm_dr->GetXaxis()->SetRangeUser(0, 15e3); htm_dr->GetYaxis()->SetRangeUser(0, 15e3);
  // h_tl->GetXaxis()->SetRangeUser(0, 15e3); h_tl->GetYaxis()->SetRangeUser(0, 15e3);
  // h_tr->GetXaxis()->SetRangeUser(0, 15e3); h_tr->GetYaxis()->SetRangeUser(0, 15e3);
  // h_al->GetXaxis()->SetRangeUser(0, 15e3); h_al->GetYaxis()->SetRangeUser(0, 15e3);
  // h_ar->GetXaxis()->SetRangeUser(0, 15e3); h_ar->GetYaxis()->SetRangeUser(0, 15e3);
  htm_pl->GetYaxis()->SetTitleOffset(1.4);   htm_pr->GetYaxis()->SetTitleOffset(1.4);
  htm_dl->GetYaxis()->SetTitleOffset(1.4);   htm_dr->GetYaxis()->SetTitleOffset(1.4);
  // h_tl->GetYaxis()->SetTitleOffset(1.4);   h_tr->GetYaxis()->SetTitleOffset(1.4);
  // h_al->GetYaxis()->SetTitleOffset(1.4);   h_ar->GetYaxis()->SetTitleOffset(1.4);
  gStyle->SetOptStat("e");
  TCanvas* cp = new TCanvas("cp", "cp", 1400, 1000); cp->Divide(2, 2);
  cp->cd(1); htm_pl->Draw("COL"); txt_l->Draw();
  cp->cd(2); htm_pr->Draw("COL"); txt_r->Draw();
  cp->cd(3); hdm_pl->Draw("COL");
  cp->cd(4); hdm_pr->Draw("COL");
  cp->SaveAs("img/TM_p.png");
  TCanvas* cd = new TCanvas("cd", "cd", 1400, 1000); cd->Divide(2, 2);
  cd->cd(1); htm_dl->Draw("COL"); txt_l->Draw();
  cd->cd(2); htm_dr->Draw("COL"); txt_r->Draw();
  cd->cd(3); hdm_dl->Draw("COL");
  cd->cd(4); hdm_dr->Draw("COL");
  cd->SaveAs("img/TM_d.png");
  // h_dl->Draw("COL"); c->SaveAs("img/SiL_TM_d.png");
  // h_dr->Draw("COL"); c->SaveAs("img/SiR_TM_d.png");
  // h_tl->Draw("COL"); c->SaveAs("img/SiL_TM_t.png");
  // h_tr->Draw("COL"); c->SaveAs("img/SiR_TM_t.png");
  // h_al->Draw("COL"); c->SaveAs("img/SiL_TM_a.png");
  // h_ar->Draw("COL"); c->SaveAs("img/SiR_TM_a.png");
}
