{
  const char IFNAME[] = "~/data/R15b/evdeal50.root";
  TFile* ifile = new TFile(IFNAME);
  TH3* evde_r0 = (TH3*)ifile->Get("evde_r0");
  TH3* evde_l0 = (TH3*)ifile->Get("evde_l0");

  gStyle->SetOptStat("e");
  TH2* hrall = (TH2*)evde_r0->Project3D("yxe");
  TH2* hlall = (TH2*)evde_l0->Project3D("yxe");
  evde_r0->GetZaxis()->SetRange(2, 5);
  evde_l0->GetZaxis()->SetRange(2, 5);
  TH2* hrcut = (TH2*)evde_r0->Project3D("yxecut");
  TH2* hlcut = (TH2*)evde_l0->Project3D("yxecut");
  hrcut->SetMaximum(hrall->GetMaximum());
  hlcut->SetMaximum(hlall->GetMaximum());
  std::cout << evde_r0->GetEntries() << " " << evde_l0->GetEntries() << " "
            << hrall->GetEntries()   << " " << (int)hlall->GetEntries()
            << std::endl;
  hrall->SetTitle("E vs dE Right (All);E_{SiR1}+E_{SiR2}[keV];E_{SiR1}[keV]");
  hlall->SetTitle("E vs dE Left (All);E_{SiL1}+E_{SiL3}[keV];E_{SiL1}[keV]");
  hrcut->SetTitle("E vs dE Right (>400 ns);E_{SiR1}+E_{SiR2}[keV];E_{SiR1}[keV]");
  hlcut->SetTitle("E vs dE Left (>400 ns);E_{SiL1}+E_{SiL3}[keV];E_{SiL1}[keV]");
  hrall->GetYaxis()->SetTitleOffset(1.4);
  hlall->GetYaxis()->SetTitleOffset(1.4);
  hrcut->GetYaxis()->SetTitleOffset(1.4);
  hlcut->GetYaxis()->SetTitleOffset(1.4);
  TH2* hrall_zoom = (TH2*)hrall->Clone("hrall_zoom");
  TH2* hlall_zoom = (TH2*)hlall->Clone("hlall_zoom");
  TH2* hrcut_zoom = (TH2*)hrcut->Clone("hrcut_zoom");
  TH2* hlcut_zoom = (TH2*)hlcut->Clone("hlcut_zoom");
  hrall_zoom->GetYaxis()->SetRangeUser(0, 3e3);
  hlall_zoom->GetYaxis()->SetRangeUser(0, 3e3);
  hrcut_zoom->GetYaxis()->SetRangeUser(0, 3e3);
  hlcut_zoom->GetYaxis()->SetRangeUser(0, 3e3);
  TCanvas* crall = new TCanvas();
  hrall->Draw("COL");
  crall->SetLogz();
  crall->SaveAs("img/data_evde_r_all.png");
  TCanvas* crall_zoom = new TCanvas();
  hrall_zoom->Draw("COL");
  crall_zoom->SetLogz();
  crall_zoom->SaveAs("img/data_evde_r_all_zoom.png");
  TCanvas* clall = new TCanvas();
  hlall->Draw("COL");
  clall->SetLogz();
  clall->SaveAs("img/data_evde_l_all.png");
  TCanvas* clall_zoom = new TCanvas();
  hlall_zoom->Draw("COL");
  clall_zoom->SetLogz();
  clall_zoom->SaveAs("img/data_evde_l_all_zoom.png");
  TCanvas* crcut = new TCanvas();
  hrcut->Draw("COL");
  crcut->SetLogz();
  crcut->SaveAs("img/data_evde_r_cut.png");
  TCanvas* crcut_zoom = new TCanvas();
  hrcut_zoom->Draw("COL");
  crcut_zoom->SetLogz();
  crcut_zoom->SaveAs("img/data_evde_r_cut_zoom.png");
  TCanvas* clcut = new TCanvas();
  hlcut->Draw("COL");
  clcut->SetLogz();
  clcut->SaveAs("img/data_evde_l_cut.png");
  TCanvas* clcut_zoom = new TCanvas();
  hlcut_zoom->Draw("COL");
  clcut_zoom->SetLogz();
  clcut_zoom->SaveAs("img/data_evde_l_cut_zoom.png");
}
