#!/bin/csh
#Usage: build <version>
#Build MIDAS standard distribution

# go to midas root
cd ..

set version = $argv[1]
set dir = /tmp/midas-$version
set archive = midas-$version.tar.gz

# create temporary directory
rm -Rf $dir
mkdir $dir

# checkout files
echo Checkout files...
cvs export -d $dir -D now midas

# add some files manually
cp doc/install.txt $dir/INSTALL
cp doc/readme.txt $dir/README
cp doc/overview.txt $dir/OVERVIEW
cp doc/CHANGELOG.TXT $dir/CHANGELOG
cp mcleanup $dir

# remove some files
rm $dir/doc/course/*.ppt

# create midas-x.xx.tar.gz file
echo Creating archive...
cd /tmp
tar -cvzf $archive midas-$version/

# remove temporary files
rm -Rf $dir

# copy to download area
cp /tmp/$archive ~/html/download/tar/$archive
cp /tmp/$archive ~/html/download/tar/midas-latest.tar.gz
cd ~/midas
cp doc/CHANGELOG.TXT ~/html/download/CHANGELOG

# remove archive
rm -f /tmp/$archive
