/********************************************************************
* /home/mulan/DAQ/www/online/wfd/./fileBjq1zj.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/mulan/DAQ/www/online/wfd/./fileBjq1zj.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablefileBjq1zj();
extern void G__cpp_setup_inheritancefileBjq1zj();
extern void G__cpp_setup_typetablefileBjq1zj();
extern void G__cpp_setup_memvarfileBjq1zj();
extern void G__cpp_setup_globalfileBjq1zj();
extern void G__cpp_setup_memfuncfileBjq1zj();
extern void G__cpp_setup_funcfileBjq1zj();
extern void G__set_cpp_environmentfileBjq1zj();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "/home/mulan/DAQ/www/online/wfd/./wfd_raw_ball.C"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__fileBjq1zjLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__fileBjq1zjLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__fileBjq1zjLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__fileBjq1zjLN_maplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;
extern G__linked_taginfo G__fileBjq1zjLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__fileBjq1zjLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
