/********************************************************************
* /home/mulan/DAQ/www/online/wfd/./fileY4ZaA5.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/mulan/DAQ/www/online/wfd/./fileY4ZaA5.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablefileY4ZaA5();
extern void G__cpp_setup_inheritancefileY4ZaA5();
extern void G__cpp_setup_typetablefileY4ZaA5();
extern void G__cpp_setup_memvarfileY4ZaA5();
extern void G__cpp_setup_globalfileY4ZaA5();
extern void G__cpp_setup_memfuncfileY4ZaA5();
extern void G__cpp_setup_funcfileY4ZaA5();
extern void G__set_cpp_environmentfileY4ZaA5();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "/home/mulan/DAQ/www/online/wfd/./wfd_raw_ball.C"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__fileY4ZaA5LN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__fileY4ZaA5LN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__fileY4ZaA5LN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__fileY4ZaA5LN_maplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;
extern G__linked_taginfo G__fileY4ZaA5LN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__fileY4ZaA5LN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
