// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /home/mulan/DAQ/www/online/wfd/./wfd_raw_ball.C;

#endif
