

// This will load all the picture book macros that you will need
void LoadPicBookMacros() {

  // Load the master function
  gROOT->ProcessLine(".L GenerateAllPlots.C+");
  
  // Load the functions individually
  gROOT->ProcessLine(".L GenerateFADCPlots.C+");
  gROOT->ProcessLine(".L GenerateDigitizerOverflowPlots.C+");
  gROOT->ProcessLine(".L GenerateRunTimePlot.C+");
  gROOT->ProcessLine(".L GenerateTDCPlots.C+");
  gROOT->ProcessLine(".L GeneratePulseShapesPlots.C+");
  gROOT->ProcessLine(".L GenerateTDiffPlots.C+");
  gROOT->ProcessLine(".L GenerateTPIPlots.C+");
  gROOT->ProcessLine(".L GenerateMuPCPlots.C+");

  gROOT->ProcessLine(".L GenerateTrendPlots.C+");

  // Load the latex macro
  gROOT->ProcessLine(".L latexWrapper.C+");

  // Load Phill's nice paletters and pick one
  gROOT->ProcessLine(".L palettes.C");
  SetUserPalette(3);

  // Now run (this file should have been generated by the .sh script)
  gROOT->ProcessLine(".x RunPicBookMacros.C");
}
