/* Generated By:JJTree&JavaCC: Do not edit this line. MqlParserConstants.java */
public interface MqlParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int IMPORT = 9;
  int NTUPLE_IMPORT = 10;
  int EXPORT = 11;
  int SELECT = 12;
  int JOIN = 13;
  int CLUSTER = 14;
  int NTUPLE = 15;
  int MERGE = 16;
  int HISTOGRAM1D = 17;
  int HISTOGRAMS1D = 18;
  int HISTOGRAM2D = 19;
  int HISTOGRAMS2D = 20;
  int HISTOGRAM3D = 21;
  int HISTOGRAMS3D = 22;
  int LITERAL = 23;
  int MODULE = 24;
  int BOOL = 25;
  int BYTE = 26;
  int SHORT = 27;
  int INT = 28;
  int FLOAT = 29;
  int DOUBLE = 30;
  int STRUCT = 31;
  int FROM = 32;
  int TO = 33;
  int BINS = 34;
  int INTO = 35;
  int WHERE = 36;
  int ENABLE = 37;
  int COINCIDENCE = 38;
  int WITH = 39;
  int MODULO = 40;
  int NAME = 41;
  int TITLE = 42;
  int UNIQUE = 43;
  int NON_TRANSITIVE = 44;
  int INVERT = 45;
  int ORDER = 46;
  int BY = 47;
  int INTEGER_LITERAL = 48;
  int DECIMAL_LITERAL = 49;
  int HEX_LITERAL = 50;
  int OCTAL_LITERAL = 51;
  int FLOATING_POINT_LITERAL = 52;
  int EXPONENT = 53;
  int CHARACTER_LITERAL = 54;
  int STRING_LITERAL = 55;
  int IDENTIFIER = 56;
  int LETTER = 57;
  int DIGIT = 58;
  int SEMICOLON = 59;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"import\"",
    "\"ntuple_import\"",
    "\"export\"",
    "\"select\"",
    "\"join\"",
    "\"cluster\"",
    "\"ntuple\"",
    "\"merge\"",
    "\"histogram1d\"",
    "\"histograms1d\"",
    "\"histogram2d\"",
    "\"histograms2d\"",
    "\"histogram3d\"",
    "\"histograms3d\"",
    "\"literal\"",
    "\"module\"",
    "\"bool\"",
    "\"byte\"",
    "\"short\"",
    "\"int\"",
    "\"float\"",
    "\"double\"",
    "\"struct\"",
    "\"from\"",
    "\"to\"",
    "\"bins\"",
    "\"into\"",
    "\"where\"",
    "\"enable\"",
    "\"coincidence\"",
    "\"with\"",
    "\"modulo\"",
    "\"name\"",
    "\"title\"",
    "\"unique\"",
    "\"non_transitive\"",
    "\"invert\"",
    "\"order\"",
    "\"by\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\"=\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
  };

}
