/* Generated By:JJTree: Do not edit this line. ./MqlParserTreeConstants.java */

public interface MqlParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTMODULEDECLARATION = 1;
  public int JJTVOID = 2;
  public int JJTBANKNAME = 3;
  public int JJTTYPE = 4;
  public int JJTCOLUMNENTRY = 5;
  public int JJTCOLUMNLIST = 6;
  public int JJTEXPRESSION = 7;
  public int JJTIMPORTSTATEMENT = 8;
  public int JJTNTUPLEIMPORTSTATEMENT = 9;
  public int JJTEXPORTSTATEMENT = 10;
  public int JJTSELECTSTATEMENT = 11;
  public int JJTWHEREEXPRESSION = 12;
  public int JJTENABLEEXPRESSION = 13;
  public int JJTMODULOEXPRESSION = 14;
  public int JJTSORTEXPRESSION = 15;
  public int JJTCOINCEXPRESSION = 16;
  public int JJTUNIQUEOPTION = 17;
  public int JJTINVERTOPTION = 18;
  public int JJTNONTRANSITIVEOPTION = 19;
  public int JJTJOINSTATEMENT = 20;
  public int JJTCLUSTERSTATEMENT = 21;
  public int JJTMERGESTATEMENT = 22;
  public int JJTNTUPLESTATEMENT = 23;
  public int JJTSTRING = 24;
  public int JJTNUMERICALEXPRESSION = 25;
  public int JJTAXIS = 26;
  public int JJTHISTOGRAMSELECTOR = 27;
  public int JJTHISTNAME = 28;
  public int JJTHISTTITLE = 29;
  public int JJTTABLENAME = 30;
  public int JJTHISTOGRAM1DSTATEMENT = 31;
  public int JJTHISTOGRAMS1DSTATEMENT = 32;
  public int JJTHISTOGRAM2DSTATEMENT = 33;
  public int JJTHISTOGRAMS2DSTATEMENT = 34;
  public int JJTHISTOGRAM3DSTATEMENT = 35;
  public int JJTHISTOGRAMS3DSTATEMENT = 36;
  public int JJTLITERALSTATEMENT = 37;


  public String[] jjtNodeName = {
    "Root",
    "ModuleDeclaration",
    "void",
    "BankName",
    "Type",
    "ColumnEntry",
    "ColumnList",
    "Expression",
    "ImportStatement",
    "NtupleImportStatement",
    "ExportStatement",
    "SelectStatement",
    "WhereExpression",
    "EnableExpression",
    "ModuloExpression",
    "SortExpression",
    "CoincExpression",
    "UniqueOption",
    "InvertOption",
    "NonTransitiveOption",
    "JoinStatement",
    "ClusterStatement",
    "MergeStatement",
    "NtupleStatement",
    "String",
    "NumericalExpression",
    "Axis",
    "HistogramSelector",
    "HistName",
    "HistTitle",
    "TableName",
    "Histogram1DStatement",
    "Histograms1DStatement",
    "Histogram2DStatement",
    "Histograms2DStatement",
    "Histogram3DStatement",
    "Histograms3DStatement",
    "LiteralStatement",
  };
}
