/********************************************************************
* DataLibraryDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DataLibraryDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDataLibraryDict();
extern void G__cpp_setup_inheritanceDataLibraryDict();
extern void G__cpp_setup_typetableDataLibraryDict();
extern void G__cpp_setup_memvarDataLibraryDict();
extern void G__cpp_setup_globalDataLibraryDict();
extern void G__cpp_setup_memfuncDataLibraryDict();
extern void G__cpp_setup_funcDataLibraryDict();
extern void G__set_cpp_environmentDataLibraryDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../../src/common/TGlobalData.h"
#include "../../src/common/TSetupData.h"
#include "../../src/common/TPulseIsland.h"
#include "../../src/common/TAnalysedPulse.h"
#include "../../src/common/TDetectorPulse.h"
#include "../../src/common/TVacuumData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DataLibraryDictLN_TClass;
extern G__linked_taginfo G__DataLibraryDictLN_TBuffer;
extern G__linked_taginfo G__DataLibraryDictLN_TMemberInspector;
extern G__linked_taginfo G__DataLibraryDictLN_TObject;
extern G__linked_taginfo G__DataLibraryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__DataLibraryDictLN_string;
extern G__linked_taginfo G__DataLibraryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DataLibraryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataLibraryDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DataLibraryDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataLibraryDictLN_lesslEstringgR;
extern G__linked_taginfo G__DataLibraryDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR;
extern G__linked_taginfo G__DataLibraryDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__DataLibraryDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DataLibraryDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DataLibraryDictLN_TH1I;
extern G__linked_taginfo G__DataLibraryDictLN_TSetupData;
extern G__linked_taginfo G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOstringgRsPgR;
extern G__linked_taginfo G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR;
extern G__linked_taginfo G__DataLibraryDictLN_pairlEstringcOstringgR;
extern G__linked_taginfo G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__DataLibraryDictLN_pairlEmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiteratorcOboolgR;
extern G__linked_taginfo G__DataLibraryDictLN_TPulseIsland;
extern G__linked_taginfo G__DataLibraryDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__DataLibraryDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataLibraryDictLN_TGlobalData;
extern G__linked_taginfo G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR;
extern G__linked_taginfo G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__DataLibraryDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgR;
extern G__linked_taginfo G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR;
extern G__linked_taginfo G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__DataLibraryDictLN_pairlEmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR;
extern G__linked_taginfo G__DataLibraryDictLN_TAnalysedPulse;
extern G__linked_taginfo G__DataLibraryDictLN_TDetectorPulse;
extern G__linked_taginfo G__DataLibraryDictLN_TVacuumData;

/* STUB derived class for protected member access */
typedef map<string,string,less<string>,allocator<pair<const string,string> > > G__maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR;
typedef pair<string,string> G__pairlEstringcOstringgR;
typedef map<string,string,less<string>,allocator<pair<const string,string> > >::iterator G__maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator;
typedef vector<TPulseIsland*,allocator<TPulseIsland*> > G__vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR;
typedef vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator G__vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator;
typedef map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > > G__maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR;
typedef pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > > G__pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR;
typedef map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator G__maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator;
