/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

#include "Riostream.h" 

#include "RooProtonESpectrum.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "Math/ProbFuncMathCore.h"

ClassImp(RooProtonESpectrum) 


//_____________________________________________________________________________
RooProtonESpectrum::RooProtonESpectrum(const char *name, const char *title, 
				       RooAbsReal& _e,
				       RooAbsReal& _t0,
				       RooAbsReal& _k,
				       RooAbsReal& _Q//,
				       //				       RooAbsReal& _Q2,
				       //				       RooAbsReal& _ARatio
				       ) :
  RooAbsPdf(name,title), 
  e("e","e",this,_e),
  t0("t0","t0",this,_t0),
  k("k","k",this,_k),
  Q("Q","Q",this,_Q)//,
//  Q2("Q2","Q2",this,_Q2),
//  ARatio("ARatio","ARatio",this,_ARatio)
{ 
} 


//_____________________________________________________________________________
RooProtonESpectrum::RooProtonESpectrum(const RooProtonESpectrum& other, const char* name) :  
  RooAbsPdf(other,name), 
  e("e",this,other.e),
  t0("t0",this,other.t0),
  k("k",this,other.k),
  Q("Q",this,other.Q)//,
  //  Q2("Q2",this,other.Q2),
  //  ARatio("ARatio",this,other.ARatio)
{ 
} 


//_____________________________________________________________________________
Double_t RooProtonESpectrum::evaluate() const 
{
  Double_t result;
  result = std::pow((1 - t0/e), k) * std::exp(-e/Q);// + ARatio*std::exp(-e/Q2);
  return result;
} 
