/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/
#ifndef ROOProtonESpectrum
#define ROOProtonESpectrum
#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
class RooProtonESpectrum : public RooAbsPdf {
 public:
  RooProtonESpectrum() {} ; 
  RooProtonESpectrum(const char *name, const char *title,
		     RooAbsReal& _e,
		     RooAbsReal& _t0,
		     RooAbsReal& _k,
		     RooAbsReal& _Q//,
		     //		     RooAbsReal& _Q2,
		     //		     RooAbsReal& _ARatio
		     );
  RooProtonESpectrum(const RooProtonESpectrum& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooProtonESpectrum(*this,newname); }
  // inline virtual ~RooProtonESpectrum() { }
    
 protected:
  RooRealProxy e ;
  RooRealProxy t0 ;
  RooRealProxy k ;
  RooRealProxy Q ;
  //  RooRealProxy Q2 ;
  //  RooRealProxy ARatio ;
  Double_t evaluate() const ;
  
 private:
  ClassDef(RooProtonESpectrum,1) // Your description goes here...
};
#endif
