/* Generated By:JJTree: Do not edit this line. MqlInvertOption.java */

public class MqlInvertOption extends SimpleNode {
  public MqlInvertOption(int id) {
    super(id);
  }

  public MqlInvertOption(MqlParser p, int id) {
    super(p, id);
  }

}
