/* Generated By:JJTree: Do not edit this line. MqlNonTransitiveOption.java */

public class MqlNonTransitiveOption extends SimpleNode {
  public MqlNonTransitiveOption(int id) {
    super(id);
  }

  public MqlNonTransitiveOption(MqlParser p, int id) {
    super(p, id);
  }

}
