/* Generated By:JJTree: Do not edit this line. MqlRoot.java */

public class MqlRoot extends SimpleNode {
  public MqlRoot(int id) {
    super(id);
  }

  public MqlRoot(MqlParser p, int id) {
    super(p, id);
  }

}
