/* Generated By:JJTree: Do not edit this line. MqlUniqueOption.java */

public class MqlUniqueOption extends SimpleNode {
  public MqlUniqueOption(int id) {
    super(id);
  }

  public MqlUniqueOption(MqlParser p, int id) {
    super(p, id);
  }

}
