{
  TFile* f = new TFile("~/R15bTME/Al50/tme09966.root");
  TTree* tr = (TTree*)f->Get("TMETree/TMETree");
  double sit[4], sil1[16], sir1[4], sir2, sir3, sil2, sil3, ge;
  int n;
  double* x;

  n = tr->Draw("SiT_1.E",   "", "goff"); x = tr->GetV1(); sit[0]   = *std::min_element(x, x+n);
  printf("SiT_1.E: %f\n", sit[0]);
  n = tr->Draw("SiT_2.E",   "", "goff"); x = tr->GetV1(); sit[1]   = *std::min_element(x, x+n);
  n = tr->Draw("SiT_3.E",   "", "goff"); x = tr->GetV1(); sit[2]   = *std::min_element(x, x+n);
  n = tr->Draw("SiT_4.E",   "", "goff"); x = tr->GetV1(); sit[3]   = *std::min_element(x, x+n);
  n = tr->Draw("SiR1_1.E",  "", "goff"); x = tr->GetV1(); sir1[0]  = *std::min_element(x, x+n);
  n = tr->Draw("SiR1_2.E",  "", "goff"); x = tr->GetV1(); sir1[1]  = *std::min_element(x, x+n);
  n = tr->Draw("SiR1_3.E",  "", "goff"); x = tr->GetV1(); sir1[2]  = *std::min_element(x, x+n);
  n = tr->Draw("SiR1_4.E",  "", "goff"); x = tr->GetV1(); sir1[3]  = *std::min_element(x, x+n);
  n = tr->Draw("SiL1_2.E",  "", "goff"); x = tr->GetV1(); sil1[1]  = *std::min_element(x, x+n);
  n = tr->Draw("SiL1_3.E",  "", "goff"); x = tr->GetV1(); sil1[2]  = *std::min_element(x, x+n);
  n = tr->Draw("SiL1_4.E",  "", "goff"); x = tr->GetV1(); sil1[3]  = *std::min_element(x, x+n);
  n = tr->Draw("SiL1_5.E",  "", "goff"); x = tr->GetV1(); sil1[4]  = *std::min_element(x, x+n);
  n = tr->Draw("SiL1_6.E",  "", "goff"); x = tr->GetV1(); sil1[5]  = *std::min_element(x, x+n);
  n = tr->Draw("SiL1_7.E",  "", "goff"); x = tr->GetV1(); sil1[6]  = *std::min_element(x, x+n);
  n = tr->Draw("SiL1_8.E",  "", "goff"); x = tr->GetV1(); sil1[7]  = *std::min_element(x, x+n);
  n = tr->Draw("SiL1_9.E",  "", "goff"); x = tr->GetV1(); sil1[8]  = *std::min_element(x, x+n);
  n = tr->Draw("SiL1_10.E", "", "goff"); x = tr->GetV1(); sil1[9]  = *std::min_element(x, x+n);
  n = tr->Draw("SiL1_11.E", "", "goff"); x = tr->GetV1(); sil1[10] = *std::min_element(x, x+n);
  n = tr->Draw("SiL1_12.E", "", "goff"); x = tr->GetV1(); sil1[11] = *std::min_element(x, x+n);
  n = tr->Draw("SiL1_13.E", "", "goff"); x = tr->GetV1(); sil1[12] = *std::min_element(x, x+n);
  n = tr->Draw("SiL1_14.E", "", "goff"); x = tr->GetV1(); sil1[13] = *std::min_element(x, x+n);
  n = tr->Draw("SiL1_15.E", "", "goff"); x = tr->GetV1(); sil1[14] = *std::min_element(x, x+n);
  n = tr->Draw("SiL3.E",    "", "goff"); x = tr->GetV1(); sil3     = *std::min_element(x, x+n);
  n = tr->Draw("SiR2.E",    "", "goff"); x = tr->GetV1(); sir2     = *std::min_element(x, x+n);
  n = tr->Draw("SiR3.E",    "", "goff"); x = tr->GetV1(); sir3     = *std::min_element(x, x+n);

  printf("SiT_1:\t%f\n",   sit [0]);
  printf("SiT_2:\t%f\n",   sit [1]);
  printf("SiT_3:\t%f\n",   sit [2]);
  printf("SiT_4:\t%f\n",   sit [3]);
  printf("SiR1_1:\t%f\n",  sir1[0]);
  printf("SiR1_2:\t%f\n",  sir1[1]);
  printf("SiR1_3:\t%f\n",  sir1[2]);
  printf("SiR1_4:\t%f\n",  sir1[3]);
  printf("SiL1_2:\t%f\n",  sil1[1]);
  printf("SiL1_3:\t%f\n",  sil1[2]);
  printf("SiL1_4:\t%f\n",  sil1[3]);
  printf("SiL1_5:\t%f\n",  sil1[4]);
  printf("SiL1_6:\t%f\n",  sil1[5]);
  printf("SiL1_7:\t%f\n",  sil1[6]);
  printf("SiL1_8:\t%f\n",  sil1[7]);
  printf("SiL1_9:\t%f\n",  sil1[8]);
  printf("SiL1_10:\t%f\n", sil1[9]);
  printf("SiL1_11:\t%f\n", sil1[10]);
  printf("SiL1_12:\t%f\n", sil1[11]);
  printf("SiL1_13:\t%f\n", sil1[12]);
  printf("SiL1_14:\t%f\n", sil1[13]);
  printf("SiL1_15:\t%f\n", sil1[14]);
  printf("SiL3:\t%f\n",    sil3);
  printf("SiR2:\t%f\n",    sir2);
  printf("SiR3:\t%f\n",    sir3);
}
